version: '3.8'

services:
  web:
    build: .
    container_name: kisaan_cv_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/SharedBackend/src
      # Redis disabled
      # - REDIS_URL=redis://redis:6379
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
